---
title: "Appendix"
output:
  pdf_document:
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "../figures/", fig.width = 5, fig.height = 5)
```

```{r read_chunks, cache=FALSE, echo=FALSE}
knitr::read_chunk("../scripts/99_utils.R")
```

```{r source_utils, message=FALSE, results='hide', echo=FALSE, warning=FALSE}
# setwd("scripts")
source("../scripts/99_utils.R")
```

```{r data_prep, fig.cap="Lake trophic state", fig.width = 6, fig.height = 3.2, warning=FALSE, message=FALSE}
lg <- lagosne_load("1.087.1")
focal_hu4s <- data.frame(hu4_zoneid = paste0("HU4_", 
                                             c("56", "57", "36", "37", "38")), 
                         stringsAsFactors = FALSE)

dt <- readRDS("../data/dt.rds") %>%
  dplyr::filter(!is.na(chla)) %>%
  mutate(trophic_state = cut(chla, 
                             breaks = c(-Inf, 2.6, 20, 56, Inf), 
                             labels = c("oligotrophic", "mesotrophic", 
                                        "eutrophic", "hypereutrophic"))) %>%
  dplyr::select(chla, trophic_state) %>%
  group_by(trophic_state) %>%
  count() %>%
  ungroup() %>% # rowwise() %>%
  mutate(frac = (n / sum(n)) * 100)

lg_trophic_state <- dplyr::filter(lg$epi_nutr, 
                                  !(lagoslakeid %in%
                                      readRDS("../data/dt.rds")$lagoslakeid)) %>%
  dplyr::filter(!is.na(chla)) %>%
  dplyr::select(chla, lagoslakeid, sampledate) %>%
  group_by(lagoslakeid) %>%
  summarise(chla = median(chla)) %>%
  mutate(trophic_state = cut(chla, 
                             breaks = c(-Inf, 2.6, 20, 56, Inf), 
                             labels = c("oligotrophic", "mesotrophic", 
                                        "eutrophic", "hypereutrophic"))) %>%
  dplyr::select(chla, trophic_state) %>%
  group_by(trophic_state) %>%
  count() %>%
  ungroup() %>% # rowwise() %>%
  mutate(frac = (n / sum(n)) * 100)

dt <- data.frame(`Trophic State` = dt$trophic_state, 
           `Study` = round(dt$frac, 1), 
           `All` = round(lg_trophic_state$frac, 1), 
           stringsAsFactors = FALSE)
dt <- setNames(dt, c("Trophic State", "This Study", "All Lakes"))


# g <- gridExtra::tableGrob(dt, rows = rep("", nrow(dt)))
# grid.draw(g)
```

```{r trophic_state, fig.cap="Lake trophic state", fig.width = 6, fig.height = 3.2, warning=FALSE, message=FALSE}
# waffle
library(waffle)
library(hrbrthemes)

dt_waffle <- tidyr::gather(dt, key = "key", value = "value", -`Trophic State`) %>%
  add_row(`Trophic State` = "oligotrophic", `key` = "All Lakes", `value` = 2) %>%
  add_row(`Trophic State` = "oligotrophic", `key` = "This Study", `value` = 2) %>%
  arrange(`Trophic State`)

ggplot(dt_waffle,
       aes(fill=`Trophic State`, values = `value`)) +
  geom_waffle(color = "white", size=0.7, n_rows = 5) +
  facet_wrap(~key, ncol = 1) +
  scale_x_discrete(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  shades::lightness(scale_fill_brewer(palette = "Greens", type = "seq"), 
                    shades::delta(-10)) +
  coord_equal() +
  theme_enhance_waffle() + 
  theme(strip.background = element_blank(), 
        rect = element_rect(fill = "transparent"), 
        legend.position = "bottom", 
        title = element_blank(), 
        strip.text = element_text(size = 16), 
        legend.text = element_text(size = 10), 
        legend.key.size = unit(0.5, "line")) + 
  guides(fill = guide_legend(nrow = 2))

# highlighted regions
test <- readRDS("../data/dt.rds") %>%
  mutate(is_focal = hu4_zoneid %in% focal_hu4s$hu4_zoneid) %>%
  dplyr::filter(!is.na(chla)) %>%
  mutate(trophic_state = cut(chla, 
                             breaks = c(-Inf, 2.6, 20, 56, Inf), 
                             labels = c("oligotrophic", "mesotrophic", 
                                        "eutrophic", "hypereutrophic"))) %>%
  dplyr::select(lagoslakeid, is_focal, chla, hu4_zoneid, trophic_state) %>%
  group_by(is_focal, trophic_state) %>%
  count() %>%
  tidyr::spread(trophic_state, n)
```

```{r predictor_maps}
# 
```