---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 6.5, fig.height = 4.5)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r 02_hierarchical_demo, echo=FALSE, message=TRUE, eval=TRUE}
# setwd("figures")
# cl            <- cart_layers()
# ep            <- cl$ep
# states        <- cl$states
# study_bbox    <- cl$study_bbox

study_bbox    <- st_read("../data/gis.gpkg", "study_bbox", quiet = TRUE)
ep            <- st_read("../data/gis.gpkg", "ep", quiet = TRUE)
states_all    <- st_read("../data/gis.gpkg", "states_all", quiet = TRUE)
hu4           <- st_read("../data/gis.gpkg", "hu4s", quiet = TRUE)

dt            <- readRDS("../data/dt.rds")
ids           <- dt %>%
  group_by(hu4_zoneid) %>% 
  tally()

hu4    <-  hu4 %>%
  # st_cast(to = "MULTIPOLYGON") %>%
  left_join(ids, by = c("ZoneID" = "hu4_zoneid"))
n_cat  <- 6
colors <- c("#FFFFFF", viridisLite::viridis(n_cat - 1))
hu4    <- mutate(hu4, 
            n_cat = cut(hu4$n, breaks = 
                          classInt::classIntervals(hu4$n, n = n_cat)$brks))
hu4    <- dplyr::filter(hu4, !is.na(n_cat))

# hist(hu4$n, n = 20)
# table(as.character(dt$hu4_zoneid))

lg <- lagosne_load("1.087.1")
ep <- left_join(dplyr::select(lg$locus, lagoslakeid, hu4_zoneid), 
                summarize(
                  group_by(dplyr::select(lg$epi_nutr, lagoslakeid, tp, chla), 
                           lagoslakeid), 
                  tp = median(tp, na.rm = TRUE), 
                  chla = median(chla, na.rm = TRUE)), 
                by = "lagoslakeid") %>%
  tidyr::drop_na() 

dt <- dplyr::select(readRDS("../data/dt.rds"), "lagoslakeid") %>% 
  left_join(ep, by = "lagoslakeid")

# hist(as.vector(table(dt$hu4_zoneid)))  
# good_hu4s <- group_by(dt, hu4_zoneid) %>% 
#   tally() %>%
#   dplyr::filter(n > 220)  
# dt <- dplyr::filter(dt, hu4_zoneid %in% good_hu4s$hu4_zoneid)
# dt <- dplyr::filter(dt, tp < 500 & chla < 150)

# create alpha sample size weightings
dt <- left_join(dt, ungroup(count(group_by(dt, hu4_zoneid))), 
                by = "hu4_zoneid") %>%
  dplyr::filter(n >= 5) %>%
  mutate(n = n / max(n, na.rm = TRUE))
  
# join iws ag
dt <- left_join(dt, ungroup(dplyr::select(mutate(
  group_by(lg$iws.lulc, lagoslakeid), 
  ag_pct = sum(iws_nlcd2011_pct_81,
                           iws_nlcd2011_pct_82, na.rm = TRUE)), 
  lagoslakeid, ag_pct))
  )

# create hu4 labels
centroid_xy <- sf::st_as_text(sf::st_geometry(sf::st_centroid(hu4[,"ZoneID"])))
extract_coords <- function(messy_centroid){
  res <- stringr::str_split(messy_centroid, "\\(", simplify = TRUE)[2]
  res <- stringr::str_split(res, "\\)", simplify = TRUE)[1]
  stringr::str_split(res, " ", simplify = TRUE)
}
coords <- data.frame(matrix(
            as.numeric(unlist(lapply(centroid_xy, extract_coords))),
            ncol = 2, byrow = TRUE), stringsAsFactors = FALSE)
names(coords) <- c("x", "y")
coords$ZoneID <- gsub("HU4_", "", hu4[,"ZoneID"]$ZoneID)

gg_lines <- ggplot(data = dt, aes(x = ag_pct, y = tp, color = hu4_zoneid, alpha = n)) + 
    # geom_point() +
    geom_line(stat = "smooth", method = lm, se = FALSE, aes(alpha = n))  +
    geom_smooth(aes(group = 1), method = lm, se = FALSE, 
                color = "black", linetype = "dashed") +
    # scale_y_log10() + scale_x_log10() +
    theme_cowplot() +
    theme(legend.position = "") +
    labs(x = "Ag. LULC (pct)", # , NLCD 2011
         y = "TP (ug/L)")  +
    scale_y_continuous(breaks = seq(0, 250, by = 50), limits = c(0, 150)) + 
    scale_color_manual(values = rep("#a50f15", 26)) 

gg_hu4 <- 
  ggplot() +
    geom_sf(data = study_bbox, alpha = 1, size = 0.6, 
              color = "black", fill = "#1D9DCF") +
    geom_sf(data = states_all, fill = "gray", color = "black", size = 0.3) +
    geom_sf(data = hu4, aes(fill = n_cat), color = "black", size = 0.4) +
  scale_fill_manual(values = c("#fee5d9", "#fcae91", "#fb6a4a", "#de2d26", "#a50f15")) +
    coord_sf(datum = NA) +
    # geom_text(data = coords, aes(x = x, y = y, label = ZoneID)) +
    theme_minimal() +
    theme(legend.position = 0,
          axis.title = element_blank(),
          legend.title = element_blank()) +
  ggtitle("# of lakes per region")

cowplot::plot_grid(gg_hu4,
  plot_grid(nullGrob(), gg_lines, nullGrob(), 
            ncol = 1, rel_heights = c(0.52, 1, 0.51)), 
  rel_widths = c(1, 0.7))
``` 
