---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 7, fig.height = 7)
source("../scripts/utils.R")
```

```{r 05_cafos, echo=FALSE, eval=TRUE}
library(LAGOSNE)
library(ggplot2)
library(dplyr)
library(tidyr)
library(concaveman)
library(sf)
library(cowplot)
# setwd("data")


states <- st_as_sf(maps::map("state", fill = TRUE, plot = FALSE))
ep      <- coordinatize(readRDS("../data/ep.rds"))
ep_bbox <- concaveman(ep)$polygons
states  <- states[unlist(lapply(st_intersects(states, ep_bbox), 
                               function(x) length(x) > 0)),]

animals <- readRDS("../data/census/census.rds")
st_geometry(animals) <- NULL
animals <- left_join(ep, animals, by = "lagoslakeid")
animals <- dplyr::filter(animals, !(lagoslakeid %in% c(401, 6076)))

# mapview::mapview(states) +
#   mapview::mapview(animals, zcol = "hog_sales")

theme_opts <- theme(legend.position = "none", 
                    axis.text = element_blank(), 
                    axis.ticks = element_blank(), 
                    title = element_text(size = 8), 
                    plot.margin = unit(c(0, -2, 0, -2), "cm"))

cowplot::plot_grid(
    ggplot() +
      geom_sf(data = states) +
      geom_sf(data = 
                dplyr::filter(animals, ), 
              aes(color = hog_sales), 
              size = 0.2, alpha = 0.8) +
      coord_sf(datum = NA) + 
      theme_minimal() + theme_opts +
      ggtitle("hog operations") +
      labs(color = paste0("hog \n operations")),
    ggplot() +
      geom_sf(data = states) +
      geom_sf(data = 
                dplyr::filter(animals, cattle_sales <= 6 & 
                                !is.na(cattle_sales)), 
              aes(color = cattle_sales), 
              size = 0.2, alpha = 0.8) +
      coord_sf(datum = NA) + 
      ggtitle("cattle operations") +
      theme_minimal() + theme_opts,
    ggplot() +
      geom_sf(data = states) +
      geom_sf(data = 
                dplyr::filter(animals, !is.na(cattle_dairy)), 
              aes(color = cattle_dairy), 
              size = 0.2, alpha = 0.8) +
      coord_sf(datum = NA) + 
      theme_minimal() + theme_opts +
      ggtitle("dairy operations") +
      labs(color = paste0("dairy \n operations")),
    ggplot() +
      geom_sf(data = states) +
      geom_sf(data = 
                dplyr::filter(animals, chicken_sales <= 30), 
              aes(color = chicken_sales), 
              size = 0.2, alpha = 0.8) +
      coord_sf(datum = NA) + 
      theme_minimal() + theme_opts +
      ggtitle("chicken operations") +
      labs(color = paste0("chicken \n operations")),
    ggplot() +
      geom_sf(data = states) +
      geom_sf(data = 
                dplyr::filter(animals, cattle_total <= 20000), 
              aes(color = cattle_total), 
              size = 0.2, alpha = 0.8, pch = 19) +
      coord_sf(datum = NA) + 
      theme_minimal() + theme_opts +
      ggtitle("cattle head") +
      labs(color = paste0("cattle \n head")), 
    ncol = 1)

# ---- debug ----
# library(mapview)
# mapview(animals, zcol = "cattle_total")
# llid <- 457
# t_iws <- dplyr::filter(iws, lagoslakeid == llid)
# t_county <- st_transform(county_sf(), st_crs(t_iws))
# t_county <- t_county[unlist(lapply(
#   st_intersects(t_county, t_iws), function(x) length(x) > 0)), ]
# t_raw <- animals_raw[unlist(lapply(
#   st_intersects(animals_raw, t_iws), function(x) length(x) > 0)), ]
# 
# mapview(t_raw) +
#   mapview(t_iws)
```
