---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 7, fig.height = 7)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r 06_lulc_buffer_demo, echo=FALSE, eval=TRUE}
# setwd("figures")

dt <- readRDS("../data/dt.rds")

llid <- dt$lagoslakeid[2]
ll_pnt <- st_coordinates(
  st_transform(
    query_gis("LAGOS_NE_All_Lakes_4ha_POINTS", "lagoslakeid", llid), 4326))
ll_lake <- st_transform(
  query_gis("LAGOS_NE_All_Lakes_4ha", "lagoslakeid", llid), 4326)
network <- extract_network(lon = ll_pnt[1], 
                                   lat = ll_pnt[2], 
                                   maxsteps = Inf, 
                           buffer_dist = units::as_units(5, "km"),
                           quiet = TRUE)
network <- network[unlist(lapply(
  st_intersects(network, st_transform(ll_lake, st_crs(network))), 
  function(x) length(x) == 0)),]

network_buffer <- st_buffer(network, 100)
nlcd           <- get_nlcd(template = as_Spatial(st_as_sfc(st_bbox(network_buffer))), 
                 label = llid)
network_buffer <- st_transform(network_buffer, projection(nlcd))

nlcd_df <- as.data.frame(nlcd, xy = TRUE) %>%
  dplyr::select(x, y, contains("Value"))
nlcd_df[,3] <- factor(nlcd_df[,3])
names(nlcd_df)[3] <- "value"
cols <- dplyr::filter(pal_nlcd(), code %in% unique(nlcd_df[,3]))


g_map <- ggplot() + 
  geom_raster(data = nlcd_df, aes(x = x, y = y, fill = value)) +
  scale_fill_manual(values = cols$color) +
  geom_sf(data = network_buffer) +
  coord_sf(datum = NULL) +
  theme(legend.position = "none", 
        axis.text = element_blank(), 
        axis.title = element_blank(), 
        line = element_blank(), 
        rect = element_blank(), 
        panel.grid = element_blank()) +
    ggtitle(paste0("llid: ", llid))

join_key <- function(vals){
  res <- vals %>%
    data.frame(code = ., stringsAsFactors = FALSE) %>% 
    count(code) %>%
    left_join(FedData::pal_nlcd(), by = "code") %>%
    dplyr::filter(code != 11)
  res$description <- factor(res$description, 
                            levels = res$description)
  res
} 

buffer_stats <- read.csv("../data/buffer_lulc.csv") %>%
  dplyr::filter(llid == 2745) %>%
  rename(total_n_lake = total_n, 
         n_lake = n) %>%
  mutate(total_n_stream = stream_buffer_area / 1000, 
         n_stream = round((percent_stream / 100) * total_n_stream, 0))

# create a vector of nlcd codes of length n_lake or n_stream
expand_nlcd_codes <- function(x, n_col){
  x_filtered <- x %>%
    dplyr::filter(!is.na(UQ(rlang::sym(n_col))))
  Map(rep, x_filtered$code, x_filtered[,n_col])  
}

lake_buffer_stats   <- join_key(as.character(unlist(
  expand_nlcd_codes(buffer_stats, "n_lake"))))
stream_buffer_stats <- join_key(as.character(unlist(
  expand_nlcd_codes(buffer_stats, "n_stream"))))
nlcd_stats          <- join_key(as.character(values(nlcd)))  

theme_opts <- theme(axis.text.x = element_blank(), 
                    legend.title = element_blank(), 
                    axis.title.x = element_blank())

g_all <- ggplot() + 
  geom_col(data = nlcd_stats, aes(x = description, 
                             y = n, 
                             fill = description)) +
  scale_fill_manual(values = nlcd_stats$color) +
  theme(legend.direction = "horizontal") +
  theme_opts +
  guides(fill = guide_legend(ncol = 2)) +
  ggtitle("Viewport LULC")

g_stream_buffer <- ggplot() + 
  geom_col(data = stream_buffer_stats, aes(x = description, 
                                  y = n, 
                                  fill = description)) +
  scale_fill_manual(values = stream_buffer_stats$color) +
  theme(legend.position = "none") +
  theme_opts +
  ggtitle("Stream buffer LULC")

g_lake_buffer <- ggplot() + 
  geom_col(data = lake_buffer_stats, aes(x = description, 
                                  y = n, 
                                  fill = description)) +
  scale_fill_manual(values = lake_buffer_stats$color) +
  theme(legend.position = "none") +
  theme_opts +
  ggtitle("Lake buffer LULC")

legend <- get_legend(g_all)

plot_grid(g_map, 
  plot_grid(g_all + theme(legend.position = "none"),
            g_lake_buffer, ggplot(),
            g_stream_buffer), 
  legend, ncol = 1) 

```

```{r buffer-lulc_vs_iws-lulc, echo=FALSE, fig.height=3}
dt <- readRDS("../data/dt.rds") %>%
  mutate(diff = stream_cultivated_crops - ag_pct) %>%
  drop_na(diff)

ggplot(data = dt) +
  geom_point(aes(x = ag_pct, y = stream_cultivated_crops, color = diff > 3)) +
  geom_abline(aes(slope = 1, intercept = 0)) +
  theme(legend.position = 0)
```

```{r satellite, echo=FALSE}
# 
# res_pnt  <- query_gis("LAGOS_NE_All_Lakes_4ha_POINTS", "lagoslakeid", 
#                       dplyr::filter(dt, diff > 0)$lagoslakeid)
res_iws  <- query_gis("IWS", "lagoslakeid", 
                      dplyr::filter(dt, diff > 3)$lagoslakeid)

# ggplot() + 
#   geom_sf(data = state_sf()) +
#   geom_sf(data = res_pnt)

library(curl)
library(glue)
library(slippymath)
library(raster)
library(rgdal)

get_image <- function(outpath, iws){
  tile_grid <- bbox_to_tile_grid(st_bbox(
    st_transform(iws, 4326)), max_tiles = 15)

  mapbox_query_string <-
    paste0("https://api.mapbox.com/v4/mapbox.satellite/{zoom}/{x}/{y}.jpg90",
           "?access_token=",
           Sys.getenv("MAPBOX_API_KEY"))
  
  images <- apply(tile_grid$tiles, 1, function(i) {
    url     <- glue(mapbox_query_string, x = i[1], y = i[2], 
                zoom = tile_grid$zoom)
    outfile <- glue("../data/mapbox/{x}_{y}.jpg", x = i[1], y = i[2])
    get_if_not_exists(url, outfile)
    return(outfile)
  })
  
  raster_out <- compose_tile_grid(tile_grid, images)
  
  writeRaster(raster_out, outpath, options="INTERLEAVE=BAND")   
  return(raster_out)
}

outpaths     <- paste0("../data/mapbox/", res_iws$lagoslakeid, ".tif")
images       <- lapply(seq_along(outpaths), function(i) 
  get_if_not_exists(get_image, outpaths[i], raster::brick, iws = res_iws[i,]))
  
iws_sized    <- which(abs(res_iws$IWSAreaHa - median(res_iws$IWSAreaHa)) < 1000)
images_sized <- images[iws_sized]

get_streams <- function(destfile){
  res <- lapply(iws_sized, function(x) 
            nhdR::nhd_plus_query(
              poly = res_iws[x,], dsn = "NHDFlowLine")$sp$NHDFlowLine)
  saveRDS(res, destfile)
  return(res)
}

res_streams <- get_if_not_exists(get_streams, "../data/nhd/res_streams.rds")

# m <- viewRGB(r) + 
#   mapview(res_streams[[1]]) + 
#   mapview(s, alpha.regions = 0, color = "red")
# 
# mapshot(m, file = paste0(getwd(), "/map.png"))
# extent(r); st_bbox(s)

i          <- 7
s          <- res_iws[iws_sized[i],]
r_raw      <- images_sized[[i]]
r          <- projectRaster(r_raw, crs = as.character(st_crs(s))[2])

tab        <- as.data.frame(r, xy = TRUE)
names(tab) <- c("x", "y", "red", "green", "blue")
tab$red   <- scales::rescale(tab$red, to = c(0, 255))
tab$blue  <- scales::rescale(tab$blue, to = c(0, 255))
tab$green <- scales::rescale(tab$green, to = c(0, 255))
tab          <- tab[complete.cases(tab),]
tab$hex      <- rgb(tab$red, tab$green, tab$blue, maxColorValue = 255)

ggplot() + 
  geom_raster(data = tab, aes(x, y, fill = I(hex))) +
  geom_sf(data = res_iws[iws_sized[i],], alpha = 0, color = "red") +
  geom_sf(data = res_streams[[i]], color = "cyan") +
  coord_sf(datum = NA) +
  theme_void()


outpaths     <- paste0("../data/mapbox/", 6201, ".tif") # good sized but low stream ag
iws_temp     <- query_gis("IWS", "lagoslakeid", 6201)
# unlink("../data/mapbox/6201.tif")
images       <- lapply(seq_along(outpaths), function(i) 
  get_if_not_exists(get_image, outpaths[i], raster::brick, iws = iws_temp))

get_streams <- function(destfile){
  res <- lapply(iws_sized, function(x) 
            nhdR::nhd_plus_query(
              poly = iws_temp, dsn = "NHDFlowLine")$sp$NHDFlowLine)
  saveRDS(res, destfile)
  return(res)
}

streams_temp <- get_if_not_exists(get_streams, "../data/nhd/temp_streams.rds")
r_raw      <- images[[1]]
r          <- projectRaster(r_raw, crs = as.character(st_crs(s))[2])

tab        <- as.data.frame(r, xy = TRUE)
names(tab) <- c("x", "y", "red", "green", "blue")
tab$red   <- scales::rescale(tab$red, to = c(0, 255))
tab$blue  <- scales::rescale(tab$blue, to = c(0, 255))
tab$green <- scales::rescale(tab$green, to = c(0, 255))
tab          <- tab[complete.cases(tab),]
tab$hex      <- rgb(tab$red, tab$green, tab$blue, maxColorValue = 255)

ggplot() + 
  geom_raster(data = tab, aes(x, y, fill = I(hex))) +
  geom_sf(data = iws_temp, alpha = 0, color = "red") +
  geom_sf(data = streams_temp[[1]], color = "cyan") +
  coord_sf(datum = NA) +
  theme_void()

```

```{r cdl_viewport}
library(raster)
library(dplyr)
library(stars)

cdl_key <- read.csv("../data/cdl/cdl_key.csv", stringsAsFactors = FALSE)

r  <- raster::raster("../data/cdl/2745.tif")

cdl_df <- as.data.frame(r, xy = TRUE) %>%
  dplyr::select(x, y, contains("2745"))
names(cdl_df)[3] <- "value"
cdl_df <- left_join(cdl_df, cdl_key, by = c("value" = "code"))

ggplot() + 
  geom_raster(data = cdl_df, aes(x = x, y = y, fill = category))

cdl_table <- as.data.frame(table(values(r)), stringsAsFactors = FALSE) %>%
    mutate(code = as.integer(Var1)) %>%
    dplyr::select(-Var1) %>%
    left_join(cdl_key, by = "code") 

test2 <- cdl_table %>% 
  dplyr::filter(description != "Background") %>%
  rename(n = Freq) %>%
  arrange(desc(n)) %>%
  group_by(category) %>%
  summarize(group_n = sum(n, na.rm = TRUE), is_ag = first(is_ag)) %>%
  ungroup() %>%
  mutate(percent = round((group_n / sum(group_n, na.rm = TRUE)) * 100, 0)) %>%
  dplyr::filter(percent >= 1) %>%
  arrange(is_ag, percent) 

test2 <- test2 %>%
  add_row(category = "crops", group_n = NA, is_ag = NA, percent = 
            sum(dplyr::filter(test2, is_ag == "ag" & 
                                category != "pasture")$percent))
  
ggplot() + 
  geom_col(data = test2, aes(x = category, 
                             y = percent, 
                             fill = category)) +
  theme(legend.direction = "horizontal", 
        legend.position = 0,
        axis.text.x = element_text(angle = 90)) +
  guides(fill = guide_legend(ncol = 2)) +
  ggtitle("CDL llid = 2745")
```


