---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.path = "../figures/", eval = TRUE, warning = FALSE, message = FALSE)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r gis_setup}
dt      <- readRDS("../data/dt.rds")
ids     <- readRDS("../data/dt.rds") %>%
  group_by(hu4_zoneid) %>% 
  tally()

hu4 <-  LAGOSNEgis::query_gis("HU4", "ZoneID", ids$hu4_zoneid) %>%
  st_cast(to = "MULTIPOLYGON") %>%
  left_join(ids, by = c("ZoneID" = "hu4_zoneid"))
n_cat  <- 6
colors <- c(#"#FFFFFF", 
            viridisLite::viridis(n_cat))
hu4    <- mutate(hu4, 
            n_cat = cut(hu4$n, breaks = 
                round(classInt::classIntervals(hu4$n, n = n_cat,
                                               style = "kmeans")$brks, 0)
                ))

hu4 <- dplyr::filter(hu4, !is.na(n_cat))
hu4 <- dplyr::left_join(hu4, 
                        distinct(dplyr::select(dt, contains("hu4_")), 
                                 hu4_zoneid, .keep_all = TRUE), 
                        by = c("ZoneID" = "hu4_zoneid"))

re_brms        <- readRDS("../data/mcmc/fe_brms_nolulc.rds")
pred_key       <- read.csv("../data/predictor_key.csv", stringsAsFactors = FALSE)
```

```{r pre_tp_fe, out.width="3.45in", out.height="4in"}
responses <- unlist(lapply(re_brms, function(x){
  get_re_response(as.character(x$formula)[1])}))

best_tp        <- which(responses == "tp")
fit_tp         <- re_brms[[best_tp]] 

# plot tp model fixed effects summary
# summary(fit_tp)

b_vars <- stringr::str_subset(
  tidybayes::get_variables(fit_tp), 
  c("^(b_)(?!.*Intercept).*$"))

gg_tp <- spread_draws(fit_tp, `b_.*`, regex = TRUE) %>%
  tidyr::gather(key = "key", value = "value", -.chain, -.iteration, -.draw) %>%
  dplyr::filter(key != "b_Intercept") %>%
  mutate(key = stringr::str_replace(key, "b_", "")) %>%
  left_join(pred_key, by = c("key" = "varv")) %>%
  group_by(pretty) %>%
  summarize(value = list(tibble::enframe(
    quantile(value, probs=c(0.05,0.5,0.95))))) %>% unnest() %>%
  tidyr::spread(name, value) %>%
  rowwise() %>%
  mutate(signif = (`5%` > 0 & `95%` > 0)| (`5%` < 0 & `95%` < 0)) %>%
  left_join(dplyr::select(pred_key, pretty, category)) %>%
  mutate(category = tidyr::replace_na(category, "Land-use cover")) %>%
  mutate(category = factor(category, 
                           levels = rev(c("Nutrient inputs", "Nutrient transport", 
                                      "Buffer configuration", "Lake", 
                                      "Land-use cover")))) %>%
  mutate(category = forcats::fct_recode(category, 
                                        Buffer = "Buffer configuration", 
                                        LULC = "Land-use cover")) %>%
  arrange(category) %>%
  ungroup() %>% mutate(pretty = factor(pretty, levels = pretty)) %>%
  arrange(category, pretty)
```

```{r pre_tn_fe, out.width="3.45in", out.height="4in"}
# lapply(re_brms, function(x) x$formula) 
# re_brms[[8]]$formula
# brms::bayes_R2(re_brms[[8]])
  
best_tn        <- which(responses == "tn")
fit_tn         <- re_brms[[best_tn]] 

# plot tn model fixed effects summary
# summary(fit_tn)
gg_tn <- spread_draws(fit_tn, `b_.*`, regex = TRUE) %>%
  tidyr::gather(key = "key", value = "value", -.chain, -.iteration, -.draw) %>%
  dplyr::filter(key != "b_Intercept") %>%
  mutate(key = stringr::str_replace(key, "b_", "")) %>%
  left_join(pred_key, by = c("key" = "varv")) %>%
  group_by(pretty) %>%
  summarize(value = list(tibble::enframe(
    quantile(value, probs=c(0.05,0.5,0.95))))) %>% unnest() %>%
  tidyr::spread(name, value) %>%
  rowwise() %>%
  mutate(signif = (`5%` > 0 & `95%` > 0)| (`5%` < 0 & `95%` < 0)) %>%
  left_join(dplyr::select(pred_key, pretty, category)) %>%
  mutate(category = tidyr::replace_na(category, "Land-use cover")) %>%
  mutate(category = factor(category, 
                           levels = rev(c("Nutrient inputs", "Nutrient transport", 
                                      "Buffer configuration", "Lake", 
                                      "Land-use cover")))) %>%
  mutate(category = forcats::fct_recode(category, 
                                        `Spatial\nconfig.` = "Buffer configuration", 
                                        LULC = "Land-use cover")) %>%
  arrange(category) %>%
  ungroup() %>% mutate(pretty = factor(pretty, levels = pretty)) %>%
  arrange(category, pretty)
```

```{r fe_axis}
# specify shared x-axis range
x_max <- c(gg_tp$`95%`, gg_tn$`95%`)[which.max(c(gg_tp$`95%`, gg_tn$`95%`))]
x_min <- c(gg_tp$`5%`, gg_tn$`5%`)[which.min(c(gg_tp$`5%`, gg_tn$`5%`))]
```

```{r tp_fe, out.width="3.45in", out.height="4in"}
(gg_tp_fe <- fe_dotplot(gg_tp, "left", cat_labels = TRUE,
                        x_min, x_max, "TP", tick_width = 2, tick_accuracy = 1, plot_padding = 13))
```

```{r tn_fe, out.width="3.45in", out.height="4in"}
(gg_tn_fe <- fe_dotplot(gg_tn, "right", cat_labels = FALSE, 
                        x_min, x_max, "TN", tick_width = 2, tick_accuracy = 1, plot_padding = 13))
```

```{r fe_nolulc, fig.width=7.5}
cowplot::plot_grid(
cowplot::plot_grid(
  equalize_panels(
    gg_tp_fe + theme(axis.title.x = element_blank())
  ), 
  equalize_panels(
    gg_tn_fe + 
      theme(axis.text.y = element_blank(), 
            axis.title.x = element_blank())), 
  rel_widths = c(1, 0.95)),

ggplot(data.frame(x = 1, y = 1, label = "Standardized coefficients", stringsAsFactors = FALSE)) + 
  geom_text(aes(x = x, y = y, label = label)) +
  theme_void(),
ncol = 1, rel_heights = c(1, 0.05))
```
