---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE, message=FALSE, echo=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 6.5, fig.height = 4.5)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r 08_exploratory_dotplot, echo=FALSE, message=TRUE, eval=TRUE, warning=FALSE, fig.height=5.5, fig.width=6.9}
pred_key <- read.csv("../data/predictor_key.csv", stringsAsFactors = FALSE)

dt       <- readRDS("../data/dt_scaled.rds")
dt_sub   <-  dt %>% 
  dplyr::select(names(.)[names(.) %in% c(pred_key$var, "tn", "tp")]) %>%
  # dplyr::select(-lagoslakeid) %>%
  # dplyr::select(tp, tn, lake_area_ha:wheat, 
  #               matches("cultivated_crops")) %>%
  # dplyr::select(-row_crop_pct, -ag_pct, -pasture_pct) %>% # rm nlcd
  # dplyr::select(-mixed.crop, -matches("other"), -forage, 
  #               -hu12_ppt_std, -water, -developed, -forest) %>% # rm junk
  # dplyr::filter(complete.cases(.)) %>%
  mutate_all(as.numeric) %>%
  janitor::remove_empty("cols") %>%
  data.frame(stringsAsFactors = FALSE)

# cor.test(dt_sub$nitrogen_atmospheric_deposition, dt_sub$tp)

dt_tp <- dt_sub %>%
  corrr::correlate() %>%
  # corrr::shave() %>%
  janitor::remove_empty(c("rows", "cols")) %>%
  mutate_if(is.numeric, round, 2) %>%
  arrange(desc(abs(tp))) %>%
  data.frame() %>%
  dplyr::select(rowname, tp, tn)

dt_tn <- dt_tp %>% 
  arrange(desc(abs(tn))) %>% 
  data.frame()

dt_tp_rows <- dt_tp$rowname
dt_tp <- dt_tp %>%
  dplyr::select(-rowname) %>%
  mutate_all(abs)
row.names(dt_tp) <- dt_tp_rows

dt_tn_rows <- dt_tn$rowname
dt_tn <- dt_tn %>%
  dplyr::select(-rowname) %>%
  mutate_all(abs)
row.names(dt_tn) <- dt_tn_rows

# ---- heatmap ----
dt_tp_hmap <- dt_sub %>%
  corrr::correlate() %>%
  # corrr::shave() %>%
  # janitor::remove_empty(c("rows", "cols")) %>%
  mutate_if(is.numeric, round, 2) %>%
  data.frame()

dt_tp_rows       <- dt_tp_hmap$rowname
dt_tp_hmap            <- dt_tp_hmap %>%
  dplyr::select(-rowname) # %>%
  # mutate_all(abs)
row.names(dt_tp_hmap) <- dt_tp_rows

# prettyfi variable labels
pretty_names <- pred_key$pretty[match(names(dt_tp_hmap), pred_key$var)] 
pretty_names <- pretty_names[!is.na(pretty_names)]
names(dt_tp_hmap)[which(!is.na(match(names(dt_tp_hmap), pred_key$var)))] <- 
  pretty_names
pretty_names <- pred_key$pretty[match(row.names(dt_tp_hmap), pred_key$var)] 
pretty_names <- pretty_names[!is.na(pretty_names)]
row.names(dt_tp_hmap)[
  which(!is.na(match(row.names(dt_tp_hmap), pred_key$var)))] <- pretty_names

# rm tp and tn also row crop ag and stream-buffer ag
dt_tp_hmap <- dplyr::select(dt_tp_hmap, -tp, -tn, 
                            -`Row-crop Ag`, -`Stream-buffer Ag`)
dt_tp_hmap <- dt_tp_hmap[!(row.names(dt_tp_hmap) %in% 
                              c("tp", "tn", "Row-crop Ag", "Stream-buffer Ag")),]

# manually sort according to the clustering shown when cluster_rows/cols TRUE
# see jsta/jsta #15 
rowcol_order <- c("Manure N", "Manure P", "Fertilizer N", 
                  "Fertilizer P", "N input", "P input", 
                  "Max depth", "Watershed-lake ratio",
                  "N deposition", "Baseflow", "Clay",
                  "Wetlands", "Pasture", "Precipitation",
                  "Soil organic carbon", "Wetland potential",
                  "Buffer natural", "Buffer Ag", "Ag", 
                  "Soybeans", "Forest", "Corn")
dt_tp_hmap <- dt_tp_hmap[match(rowcol_order, row.names(dt_tp_hmap)),]
dt_tp_hmap <- dt_tp_hmap[,match(rowcol_order, names(dt_tp_hmap))]

dt_tp_hmap_abs <- mutate_all(dt_tp_hmap, abs) %>%
  data.frame()
row.names(dt_tp_hmap_abs) <- rowcol_order
pheatmap::pheatmap(
  t(dt_tp_hmap_abs),
  color = colorRampPalette(RColorBrewer::brewer.pal(n = 7, name =
                                            "Reds"))(100),
  cluster_cols = TRUE, cluster_rows = TRUE,
  na.col = "grey",
  cellheight = 7)

pheatmap::pheatmap(
  t(dt_tp_hmap),
  # color = colorRampPalette(RColorBrewer::brewer.pal(n = 7, name =
  #                                          "Reds"))(100),
  cluster_cols = TRUE, cluster_rows = TRUE,
  na.col = "grey",
  cellheight = 7, cellwidth = 7)
```

\pagebreak
```{r dotplot, message=FALSE, echo=FALSE, warning=FALSE}
# ---- dotplot ----

prep_dotplot <- function(x, col_name){
  # x <- dt_tp
  # col_name <- "tp"
  pred_key <- read.csv("../data/predictor_key.csv", stringsAsFactors = FALSE)
  res      <- x %>%
    dplyr::select(UQ(rlang::sym(col_name))) %>%
    # dplyr::filter(!is.na(UQ(rlang::sym(col_name)))) %>%
    dplyr::mutate(var = row.names(x)) %>%
    dplyr::left_join(pred_key, by = "var") %>%
    dplyr::mutate(var = factor(row.names(x), 
                            levels = rev(row.names(x))), 
                  pretty = factor(pretty, levels = rev(pretty)),
                  category = factor(category, 
                                    levels = c("Nutrient inputs",
                                               "Nutrient transport", 
                                               "Land-use cover",
                                               "Buffer configuration", 
                                               "Lake"))) %>%
    dplyr::filter(!(var %in% c("tp", "tn"))) %>%
    dplyr::filter(!is.na(category))
  res
}

dt_tp <- prep_dotplot(dt_tp, "tp") %>%
  dplyr::filter(!str_detect(pretty, "^N ")) %>%
  dplyr::filter(!str_detect(pretty, " N ")) %>%
  dplyr::filter(!(pretty %in% c("Stream-buffer Ag", 
                                          "N input", "P input")))

dt_tn <- prep_dotplot(dt_tn, "tn") %>%
  dplyr::filter(!str_detect(pretty, "^P ")) %>%
  dplyr::filter(!str_detect(pretty, " P ")) %>%
  dplyr::filter(!(pretty %in% c("Stream-buffer Ag", 
                                          "N input", "P input")))

# head(prep_dotplot(dt_tp, "tp"))
# show_col(brewer_pal("div", "Set1")(4))                   
plot_opts <- theme_cowplot() +
  theme(axis.title.y = element_blank(), 
        axis.text = element_text(size = 8), 
        axis.title.x = element_blank())

gg_tp <-  ggplot(data = dt_tp) + 
    geom_point(aes(x = tp, y = pretty, color = category)) + 
    scale_color_brewer(palette = "Set1") +
    xlim(0, 0.6) +
    plot_opts +
  theme(legend.text = element_text(size = 8), 
        legend.position = c(0.53, 0.23), 
        legend.box.background = element_rect(color = "black"), 
        legend.title = element_blank())
gg_tn <- ggplot(data = dt_tn) + 
    geom_point(aes(x = tn, y = pretty, color = category)) +
    scale_color_brewer(palette = "Set1") +
    xlim(0, 0.6) +
    plot_opts +
  theme(legend.position = 0)

plot_grid(NULL, 
plot_grid(gg_tp, NULL,
          gg_tn, rel_widths = c(1, 0.2, 1), nrow = 1, 
          labels = c("TP", "", "TN"), 
          label_x = c(0.6, 0.5, 0.6), 
          label_y = c(1.05, 1.1, 1.05)), 
ncol = 1, rel_heights = c(0.07, 1))

row_highlight <- function(x, gg){
  # x <- "Fertilizer"
  if(!(x %in% gg$data$pretty)){
    x <- as.character(gg$data$pretty[grep(x, gg$data$pretty)])
  }
  
  gg + 
    scale_color_manual(values = rep("black", 5)) +
    gghighlight(pretty == x, use_direct_label = FALSE)  
}

dotplot_panel <- function(x){
  plot_grid(NULL, 
plot_grid(row_highlight(x, gg_tp) + theme(legend.position = 0), NULL,
          row_highlight(x, gg_tn), 
          rel_widths = c(1, 0.2, 1), nrow = 1, 
          labels = c("TP", "", "TN"), 
          label_x = c(0.6, 0.5, 0.6), 
          label_y = c(1.05, 1.1, 1.05)), 
ncol = 1, rel_heights = c(0.07, 1))
}

dotplot_panel("Max depth")
dotplot_panel("Baseflow")
dotplot_panel("Corn")
dotplot_panel("Fertilizer")
dotplot_panel("Buffer Ag")
```

\pagebreak
```{r densityplots, message=FALSE, echo=FALSE, warning=FALSE}
# ---- densityplots ----
library(ggforce)

ggplot(data = tidyr::gather(dt_sub)) +
  geom_density(aes(value)) +
  facet_wrap_paginate(~key, scales = "free", ncol = 2, nrow = 4, page = 1)
ggplot(data = tidyr::gather(dt_sub)) +
  geom_density(aes(value)) +
  facet_wrap_paginate(~key, scales = "free", ncol = 2, nrow = 4, page = 2)
ggplot(data = tidyr::gather(dt_sub)) +
  geom_density(aes(value)) +
  facet_wrap_paginate(~key, scales = "free", ncol = 2, nrow = 4, page = 3)

```
