---
output: pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../figures/", fig.width = 6.5, fig.height = 4.5)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r 10_nitrogen_deposition, echo=FALSE, message=TRUE, eval=TRUE}
dt     <- readRDS("../data/dt.rds")
dt_sub <- dt %>% 
  dplyr::select(tp, tn, lake_area_ha:wheat, 
                matches("cultivated_crops")) %>%
  dplyr::select(-row_crop_pct, -ag_pct, -pasture_pct) %>% # rm nlcd
  dplyr::select(-mixed.crop, -matches("other"), -forage, 
                -hu12_ppt_std, -water, -developed, -forest) %>% # rm junk
  dplyr::filter(complete.cases(.)) %>%
  mutate_all(as.numeric) %>%
  data.frame(stringsAsFactors = FALSE)

slice_cormat <- function(var_name, dt_sub){
  # var_name <- "nitrogen_atmospheric_deposition"

  dt_corr <- dt_sub %>%
    corrr::correlate() %>%
    # corrr::shave() %>%
    janitor::remove_empty(c("rows", "cols")) %>%
    mutate_if(is.numeric, round, 2) %>%
    arrange(desc(abs(!!rlang::sym(var_name)))) %>%
    data.frame() %>%
    dplyr::select(rowname, var_name)

  dt_corr_rows <- dt_corr$rowname
  dt_corr <- dt_corr %>%
    dplyr::select(-rowname) %>%
    mutate_all(abs)
  row.names(dt_corr) <- dt_corr_rows

  dt_corr
}

prep_dotplot <- function(x, col_name){
  dplyr::select(x, UQ(rlang::sym(col_name))) %>% 
    dplyr::mutate(var = factor(row.names(x), 
                            levels = rev(row.names(x)))) %>%
    dplyr::filter(!(var %in% c("tp", "tn")))
}

dt_ndep <- slice_cormat("nitrogen_atmospheric_deposition", dt_sub)

ggplot(data = prep_dotplot(dt_ndep, "nitrogen_atmospheric_deposition")) +
    geom_point(aes(x = nitrogen_atmospheric_deposition, y = var))

# ---- scatterplots ----
# plot n_dep vs ppt
# plot n_dep vs baseflow

# plot(lg$hu12.chag$hu12_dep_totaln_2010_mean, 
#      lg$hu12.chag$hu12_prism_ppt_30yr_normal_800mm2_annual_mean)

# ggplot(data = dt_sub) + 
#   geom_point(aes(x = ))

# ---- autocorrelation_plots ----
# spind::acfft()

``` 


