---
output:
  pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
```

```{r cdl_key, eval=TRUE}
library(kableExtra)
library(dplyr)

# setwd("tables")
# ---- cdl_key ----
cdl_key <- read.csv("../data/cdl/cdl_key.csv", stringsAsFactors = FALSE)
# (example_full <- cdl_key %>%
#   group_by(category) %>%
#   sample_n(1) %>%
#   arrange(is_ag, code) %>%
#   dplyr::select(-is_forage) %>%
#   dplyr::select(category, ag = is_ag, example = description, code) %>%
#   knitr::kable(digits = 0, format = "markdown", caption = "Example of all CDL categorizations."))

(example_filtered <- 
  cdl_key %>%
  dplyr::filter(category %in% c("corn", "soybeans", "forest", "wetlands", "pasture")) %>%
  arrange(category) %>%
  select(category, description) %>%
  mutate_all(snakecase::to_sentence_case) %>%
  setNames(snakecase::to_sentence_case(names(.))) %>%
  knitr::kable(digits = 0, format = "markdown", caption = "CDL categorizations. See code supplement for listing of variables classified as 'ag'"))
  
  
```

\pagebreak
```{r cdl_summary, eval=FALSE}
# setwd("tables")
# ---- cdl summary ----
cdl_data <- read.csv("../data/cdl/cdl_summary.csv", stringsAsFactors = FALSE)

dt <- apply(cdl_data, 2, function(x) quantile(x, c(0.05, 0.5, 0.95), 
                                        na.rm = TRUE)) %>%
  data.frame() %>%
  dplyr::select(-llid)
  
dt %>%
  t() %>%
  knitr::kable(caption = "CDL summary statistics", digits = 2,
               format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = c("hold_position"), full_width = FALSE) %>%
  add_header_above(c(" ", "Quantiles" = 3))
```
