---
output:
  pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
# setwd("tables")
source("../scripts/99_utils.R")
```

```{r summary_table, eval=TRUE}
# setwd("tables")
re_brms <- readRDS("../data/mcmc/re_brms.rds")

# filter out row crop from r2_brms
predictors <- unlist(lapply(re_brms, function(x) get_re_text(
  as.character(x$formula)[[1]])))
re_brms    <- re_brms[-1 * which(predictors == "rowvcropvpct")]
predictors <- unlist(lapply(re_brms, function(x) get_re_text(
  as.character(x$formula)[[1]])))

# get responses
response <- unlist(lapply(re_brms, function(x) get_re_response(
  as.character(x$formula)[[1]])))

loo_re <- rbind(
  loo_compare(lapply(which(response == "tp"), function(x) re_brms[[x]]$loo)), 
  loo_compare(lapply(which(response == "tn"), function(x) re_brms[[x]]$loo))) 
loo_re_df            <- data.frame(loo_re)
row.names(loo_re_df) <- NULL
loo_re_df$term       <- row.names(loo_re)
loo_re_df$response   <- response

dt <- dplyr::bind_rows(lapply(re_brms, function(x) x$R2))
dt <- left_join(loo_re_df, dt, by = c("term", "response"))
dt <- dplyr::select(dt, 
                    response, term, r2 = Estimate, elpd_diff)
dt <- dt[order(dt$response, dt$elpd_diff, decreasing = c(TRUE, FALSE)),]

options(knitr.kable.NA = "-")  
dt %>%
  # dplyr::filter(str_detect(response, "tp")) %>%
  # dplyr::select(-response) %>%
  dplyr::rename("$R^2$" = r2, 
                "LOO-ELPD" = elpd_diff) %>%
  knitr::kable(digits = 2, format = "markdown", caption = "TP Model R2", 
               row.names = FALSE)
```

\pagebreak
```{r tn_results, eval=FALSE}
dplyr::filter(dt, str_detect(response, "tn")) %>%
  dplyr::select(-response) %>%
  dplyr::rename("$R^2$" = r2) %>%
  knitr::kable(digits = 2, format = "markdown", caption = "TN Model R2")
```
