---
output:
  pdf_document
header-includes: 
  - \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE, fig.path = "../figures/", fig.width = 5, fig.height = 6)
# setwd("figures")
source("../scripts/99_utils.R")
```

```{r summary_table, eval=TRUE}
library(kableExtra)
library(dplyr)
library(magrittr)

lg <- lagosne_load("1.087.1")
focal_hu4s <- data.frame(hu4_zoneid = paste0("HU4_", 
                                             c("56", "57", "36", "37", "38")), 
                         stringsAsFactors = FALSE)

compare_focal <- function(dt, ids, threshold = 0){
  dt <- dt %>%
  mutate(is_focal = hu4_zoneid %in% ids) %>% 
  group_by(is_focal) %>%
  summarize_all(median, na.rm = TRUE) %>%
  tidyr::gather(key = "key", value = "value", -is_focal) %>%
  dplyr::filter(!is.na(value)) %>%
  dplyr::filter(value != 0) %>%
  tidyr::spread(key, value) %>%
  t()

  row_names <- row.names(dt)

  res <- dt %>%
    data.frame(stringsAsFactors = FALSE) %>%
    setNames(c("nonfocal", "focal")) %>%
    mutate_all(~as.numeric(.)) %>%
    mutate(var = row_names) %>%
    mutate(diff = abs(abs(nonfocal - focal)/nonfocal)) %>%
    dplyr::filter(!is.na(diff)) %>%
    dplyr::filter(diff > threshold) %>%
    arrange(desc(diff)) %>%
    mutate_if(is.numeric, ~format(., scientific = FALSE)) 
  
  res
}

hu4 <- lg$hu4 %>%
  left_join(lg$hu4.chag) %>%
  left_join(lg$hu4.conn) %>%
  # left_join(lg$hu4.lulc) %>%
  dplyr::filter(hu4_zoneid %in% unique(readRDS("../data/dt.rds")$hu4_zoneid)) %>%
  dplyr::select(-matches("count")) %>%
  dplyr::select(-matches("nwi")) %>%
  dplyr::select(-matches("lakes10ha")) %>%
  dplyr::select(-matches("std")) %>%
  dplyr::select(-matches("min")) %>%
  dplyr::select(-matches("max")) %>%
  dplyr::select(-matches("canalditchdensity")) %>%
  dplyr::select(-matches("wetlandsundissolved")) %>%
  dplyr::select(-matches("overlapping")) %>%
  dplyr::select(-matches("contributing")) %>%
  dplyr::select(-matches("1985|1990|1995|2000|2005")) %>%
  dplyr::select(-matches("_ha")) %>%
  compare_focal(focal_hu4s$hu4_zoneid, threshold = 0.011)
  

dt        <- suppressWarnings(
  compare_focal(readRDS("../data/dt.rds"), focal_hu4s$hu4_zoneid, threshold = 0.28))
dt_scaled <- suppressWarnings(
  compare_focal(readRDS("../data/dt_scaled.rds"), focal_hu4s$hu4_zoneid, threshold = 0.9))

jsta::pdf_table(dt, "../tables/dt.pdf")
jsta::pdf_table(dt_scaled, "../tables/dt_scaled.pdf")
jsta::pdf_table(hu4, "../tables/hu4.pdf")

View(dt)

knitr::kable(dt, digits = 0, format = "markdown") 
#%>%
 # add_header_above(c(" ", " ", Ranges = 3, " ", " "))
```
